name: Build on Ubuntu 24.10

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
           file: docker/ubuntu/Dockerfile2410
           load: true
           cache-from: type=gha,scope=cgimap:2410
           cache-to: type=gha,mode=max,scope=cgimap:2410
           tags: cgimap:2410

      - name: Running Docker image
        run: |
           docker run --entrypoint /bin/bash cgimap:2410 -c "/usr/local/bin/openstreetmap-cgimap --help"
